[Draft][Localization][KO] Mystery Encounters Translations
Adri1/pokerogue pull request #13
Opened 2024-09-15 02:08 UTC by KimJeongSun

- [ ] a-trainers-test-dialogue.json 
- [x] absolute-avarice-dialogue.json :  sodam #5
- [x] an-offer-you-cant-refuse-dialogue.json :sodam #4 
- [x] berries-abound-dialogue.json :sodam #5
- [ ] bug-type-superfan-dialogue.json
- [ ] clowning-around-dialogue.json
- [x] dancing-lessons-dialogue.json :sodam #4
- [x] dark-deal-dialogue.json #1 ( merged )
- [x] delibirdy-dialogue.json :sodam #5 
- [x] department-store-sale-dialogue.json :  sodam #6 
- [x] field-trip-dialogue.json :sodam #7
- [ ] fiery-fallout-dialogue.json
- [x] fight-or-flight-dialogue.json :sodam #6
- [ ] fun-and-games-dialogue.json
- [ ] global-trade-system-dialogue.json
- [x] lost-at-sea-dialogue.json :  sodam #7 
- [x] mysterious-challengers-dialogue.json :sodam #7 
- [x] mysterious-chest-dialogue.json :  sodam #6 
- [ ] part-timer-dialogue.json
- [ ] safari-zone-dialogue.json
- [ ] shady-vitamin-dealer-dialogue.json
- [ ] slumbering-snorlax-dialogue.json
- [ ] teleporting-hijinks-dialogue.json
- [ ] the-pokemon-salesman-dialogue.json
- [ ] the-strong-stuff-dialogue.json
- [ ] the-winstrate-challenge-dialogue.json
- [ ] training-session-dialogue.json
- [x] trash-to-treasure-dialogue.json : #4  :sodam
- [ ] uncommon-breed-dialogue.json
- [ ] weird-dream-dialogue.json

2024-09-16 01:13 UTC, KimJeongSun commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "황금 잠자리채", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 묘한 무게감이 든다." }
```suggestion
    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "황금잠자리채", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 묘한 무게감이 든다." }
```

2024-09-16 01:16 UTC, KimJeongSun commented on src/locales/ko/modifier-select-ui-handler.json
> +  "continueNextWaveDescription": "다음 웨이브로 진행한다."
```suggestion
  "continueNextWaveDescription": "다음 웨이브로 진행합니다."
```

2024-09-17 12:33 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "당신 쓰레기 더미를 헤집고다니며, 오물을 뒤집어썼다.$지금 이 상태로는,\n아무리 친절한 점원이라도 아무것도 안 팔 것 같다!$앞으로 상점에서 파는 회복약 없이 버텨야 한다.$하지만, 쓰레기에서 엄청난 물건들을 발견했다!"
```suggestion
      "tooltip": "(-) 회복 아이템 가격 3배로 변경\n(+) 끝내주는 아이템들을 획득",
      "selected": "쓰레기 더미를 헤집고다니며, 오물을 뒤집어썼다.$지금 이 상태로는,\n아무리 친절한 점원이라도 물건을 제 가격에 안 팔 것 같다!$앞으로 상점에서 파는 회복약을 훨씬 비싸게 사야 한다.$하지만, 쓰레기에서 엄청난 물건들을 발견했다!"
```

2024-09-17 12:39 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "당신 쓰레기 더미를 헤집고다니며, 오물을 뒤집어썼다.$지금 이 상태로는,\n아무리 친절한 점원이라도 아무것도 안 팔 것 같다!$앞으로 상점에서 파는 회복약 없이 버텨야 한다.$하지만, 쓰레기에서 엄청난 물건들을 발견했다!"
thanks

2024-09-18 05:06 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
>    "egg_list_full_dialogue": "Oh, it looks like you don't have room to carry another egg.$Here, take these instead!",
```suggestion
  "egg_list_full_dialogue": "앗, 너 새로운 알을 받을 자리가 없어 보이는구나.$자, 대신 이걸 줄게!",
```

2024-09-18 05:21 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족값이 {{reductionValue}}만큼 감소했다!$하지만 다른 포켓몬들은 놀라울만
```suggestion
      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족값이 각각 {{reductionValue}}만큼 감소했다!$하지만 다른 포켓몬들은 놀라울만큼 활력이 넘친다!\n다른 포켓몬들의 종족값이 각각 {{increaseValue}}만큼 증가했다!"
```

2024-09-18 05:51 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "description": "{{strongestPokemon}}[[를]] 넘기는 대신\n@[TOOLTIP_TITLE]{Shiny Charm}과 {{price, money}}을 준다고 합니다!\n\n매우 좋은 조건이지만,\n이렇게 든든한 동료를 보내줘야 할까요?",
```suggestion
  "description": "{{strongestPokemon}}[[를]] 넘기는 대신\n@[TOOLTIP_TITLE]{빛나는부적}과 {{price, money}}을 준다고 합니다!\n\n매우 좋은 조건이지만,\n이렇게 든든한 동료를 보내줘야 할까요?",
```
툴팁수정

2024-09-18 05:52 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "tooltip": "(-) {{strongestPokemon}}[[를]] 보내줌\n(+) @[TOOLTIP_TITLE]{Shiny Charm}[[를]] 획득\n(+) {{price, money}}[[를]] 획득",
```suggestion
      "tooltip": "(-) {{strongestPokemon}}[[를]] 보내줌\n(+) @[TOOLTIP_TITLE]{빛나는부적}[[를]] 획득\n(+) {{price, money}}[[를]] 획득",
```

2024-09-18 05:52 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "tooltip": "(-) {{strongestPokemon}}[[를]] 보내줌\n(+) @[TOOLTIP_TITLE]{Shiny Charm}[[를]] 획득\n(+) {{price, money}}[[를]] 획득",
테스트 영상까지 찍었는데 이걸 못봤네요

2024-09-18 05:53 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +      "tooltip": "(-) 힘든 전투\n(+) @[TOOLTIP_TITLE]{Very Rare Egg} 획득"
```suggestion
      "tooltip": "(-) 힘든 전투\n(+) @[TOOLTIP_TITLE]{매우 희귀한 알} 획득"
```

2024-09-18 05:53 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +      "tooltip": "(+) 파티 전체 회복\n(+) @[TOOLTIP_TITLE]{Egg} 획득"
```suggestion
      "tooltip": "(+) 파티 전체 회복\n(+) @[TOOLTIP_TITLE]{알} 획득"
```

2024-09-18 05:56 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/the-winstrate-challenge-dialogue.json
> +      "tooltip": "(+) 파티 전체 회복\n(+) 더희귀한사탕 획득",
```suggestion
      "tooltip": "(+) 파티 전체 회복\n(+) 더이상한사탕 획득",
```
레어캔디 업그레이드버전

2024-09-18 06:01 UTC, sodaMelon commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "tooltip": "(-) 회복 아이템 가격 3배로 변경\n(+) 끝내주는 아이템들을 획득",
```suggestion
      "tooltip": "(-) 회복 아이템 가격 3배 상승\n(+) 끝내주는 아이템들을 획득",
```
좀더 명확한 문장

2024-09-18 06:07 UTC, sodaMelon approved these changes
LGTM

2024-09-18 09:52 UTC, returntoice requested changes

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "우왓!\n연료가 다 떨어졌나본데?"
```suggestion
      "1": "우왓!\n연료가 다 떨어졌나 본데?",
      "2": "우왓!\n연료가 다 떨어졌나 본데?"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "더는 헤매거나 하지 않는다는 것을 너에게 보여줄게!"
```suggestion
      "2": "더는 헤매거나 하지 않는다는 것을 너에게 보여 줄게!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "…좋아.\n난…지지않아…!"
```suggestion
      "2": "…좋아.\n난…지지 않아…!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "2": "꽤 인상적인 실력이었어.\n다음엔 더 잘해봐."
```suggestion
      "1": "꽤 인상적인 실력이었어.\n다음엔 더 잘해 봐.",
      "2": "꽤 인상적인 실력이었어.\n다음엔 더 잘해 봐."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/dialogue.json
> +      "1": "난 우리 가족 중에서도 제일 강했어.\n한 번도 져본 적이 없었는데…"
```suggestion
      "1": "난 우리 가족 중에서도 제일 강했어.\n한 번도 져 본 적이 없었는데…"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/modifier-select-ui-handler.json
> +  "continueNextWaveButton": "진행하기",
지금 이거 어느 버튼으로 나오는지는 모르겠지만 일반적인 선택 버튼이면 '진행한다'가 낫지 않을까요?

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "황금잠자리채", "description": "벌레타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 묘한 무게감이 든다." }
```suggestion
    "MYSTERY_ENCOUNTER_GOLDEN_BUG_NET": { "name": "황금잠자리채", "description": "벌레 타입 포켓몬을 더 자주 만날 수 있는 행운을 부여한다. 묘한 무게감이 든다." }
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounter-messages.json
> +  "cancel_option": "조우 선택지로 돌아가기",
이것 역시 '~한다' 형태로 하는 게 좋지 않을까 생각이 듭니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +    "intro_dialogue": "안녕, 내 이름은 모미야.$너처럼 강한 트레이너가\n관심 있을만한 제안이 있어.$희귀한 알을 두 개 가지고 있는데,\n하나를 누가 맡아줬으면 해.$네가 승부에서 이긴다면,\n더 희귀한 알을 너한테 맡기도록 할게!",
```suggestion
    "intro_dialogue": "안녕, 내 이름은 모미야.$너처럼 강한 트레이너가\n관심 있을 만한 제안이 있어.$희귀한 알을 두 개 가지고 있는데,\n하나를 누가 맡아줬으면 해.$네가 승부에서 이긴다면,\n더 희귀한 알을 너한테 맡기도록 할게!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +    "decline": "알았어.\n네 포켓몬들 좀 지쳐보이네.$자, 내가 좀 도와줄게."
```suggestion
    "decline": "알았어.\n네 포켓몬들 좀 지쳐 보이네.$자, 내가 좀 도와줄게."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +    "accept": "승부하는거지?\n야호!",
```suggestion
    "accept": "승부하는 거지?\n야호!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +    "decline": "어라, 승부 안 하는거야?\n괜찮아!$미루가 네 포켓몬들을 치료해줄게!"
```suggestion
    "decline": "어라, 승부 안 하는 거야?\n괜찮아!$미루가 네 포켓몬들을 치료해 줄게!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/a-trainers-test-dialogue.json
> +  "description": "이 트레이너는 승부를 받아들이든 거절하든 알을 줄 것 같습니다.\n하지만 이 강한 트레이너를 쓰러트릴 수 있다면 훨씬 더 희귀한 알을 받을 수 있을 겁니다.",
```suggestion
  "description": "이 트레이너는 승부를 받아들이든 거절하든 알을 줄 것 같습니다.\n하지만 이 강한 트레이너를 쓰러트린다면 훨씬 더 희귀한 알을 받을 수 있을 겁니다.",
```
실제로 쓰러트려야 희귀 알을 얻을 수 있는 것이기 때문에 깔끔하게 '쓰러트린다면'으로 하는 것이 더 자연스럽다고 생각합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "당신이 방심한 틈에 {{greedentName}}[[가]] 나무열매를 모두 훔쳐가버렸습니다!\n\n{{greedentName}}[[는]] 나무열매를 먹으려다가,\n잠시 멈춰서 당신을 재밌다는 듯 바라보고 있습니다.",
```suggestion
  "description": "당신이 방심한 틈에 {{greedentName}}[[가]] 나무열매를 모두 훔쳐가 버렸습니다!\n\n{{greedentName}}[[는]] 나무열매를 먹으려다가,\n잠시 멈춰서 당신을 재밌다는 듯 바라보고 있습니다.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +      "selected": "{{greedentName}}[[가]] 눈 깜짝할 새에\n모든 나무열매를 먹어치웠다!$흡족하게 이쪽을 바라보면서,\n빵빵해진 배를 두드렸다.$아마 앞으로 식비가 만만치 않을 것 같다…$@s{level_up_fanfare}{{greedentName}}[[는]] 동료가 되고 싶어하는 것 같다!"
```suggestion
      "selected": "{{greedentName}}[[가]] 눈 깜짝할 새에\n모든 나무열매를 먹어치웠다!$흡족하게 이쪽을 바라보면서\n빵빵해진 배를 두드렸다.$아마 앞으로 식비가 만만치 않을 것 같다…$@s{level_up_fanfare}{{greedentName}}[[는]] 동료가 되고 싶어하는 것 같다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +  "intro_dialogue": "안녕하세요.$당신의 {{strongestPokemon}}[[가]] 정말 멋져서 그냥 지나칠수가 없네요!$항상 저런 애완 포켓몬을 갖고 싶었거든요!$제가 오래된 장신구랑\n돈도 함께 섭섭지 않게 챙겨주도록 하죠!",
```suggestion
  "intro_dialogue": "안녕하세요.$당신의 {{strongestPokemon}}[[가]] 정말 멋져서 그냥 지나칠 수가 없네요!$항상 저런 애완 포켓몬을 갖고 싶었거든요!$제가 오래된 장신구랑\n돈도 함께 섭섭지 않게 챙겨주도록 하죠!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "label": "꼬마녀석을 혼내준다",
```suggestion
      "label": "꼬마 녀석을 혼내준다",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/an-offer-you-cant-refuse-dialogue.json
> +      "selected": "말도 안 돼!\n{{liepardName}}, 우리 지금 삥 뜯긴거야?!$너...!\n곧 우리 변호사 연락을 받게 될 거다!"
```suggestion
      "selected": "말도 안 돼!\n{{liepardName}}, 우리 지금 삥 뜯긴 거야?!$너…!\n곧 우리 변호사 연락을 받게 될 거다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +  "description": "나무열매 덤불을 지키고 있는 강력한 포켓몬이 있는 것 같습니다.\n그냥 싸워볼 수도 있겠지만, 조금 강해보입니다.\n혹시 빠른 포켓몬이라면 잡히지 않고 열매를 가져올 수 있지 않을까요?",
```suggestion
  "description": "나무열매 덤불을 지키고 있는 강력한 포켓몬이 있는 것 같습니다.\n그냥 싸워 볼 수도 있겠지만, 조금 강해 보입니다.\n혹시 빠른 포켓몬이 있다면 잡히지 않고도 열매를 가져올 수 있지 않을까요?",
```
의미를 조금 명확하게 고쳐 보았습니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/berries-abound-dialogue.json
> +      "selected_bad": "{{fastestPokemon}}[[가]] 나무열매 덤불을 행해 달려간다!$이런! {{enemyPokemon}}[[가]] 더 빨라서, 가로막혔다!",
```suggestion
      "selected_bad": "{{fastestPokemon}}[[가]] 나무열매 덤불을 향해 달려간다!$이런! {{enemyPokemon}}[[가]] 더 빨라서 가로막혔다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +  "intro_dialogue": "거기, 트레이너!\n난 세상에서 가장 희귀한 벌레 포켓몬을 찾고있어!$너도 벌레 타입 포켓몬 좋아하지?\n모두 벌레 타입 포켓몬을 좋아하니깐!",
```suggestion
  "intro_dialogue": "거기, 트레이너!\n난 세상에서 가장 희귀한 벌레 포켓몬을 찾고 있어!$너도 벌레 타입 포켓몬 좋아하지?\n모두 벌레 타입 포켓몬을 좋아하니깐!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +  "speaker": "벌레타입 매니아",
```suggestion
  "title": "벌레 타입 포켓몬 매니아",
  "speaker": "벌레 타입 매니아",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +  "description": "이 트레이너는 대답할 틈도 없이, 계속 떠들어대고 있습니다…\n\n이 상황에서 벗어나려면, 트레이너의 주의를 돌려야 할 것 같습니다!",
```suggestion
  "description": "이 트레이너는 대답할 틈도 없이 계속 떠들어대고 있습니다…\n\n이 상황에서 벗어나려면, 트레이너의 주의를 돌려야 할 것 같습니다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +      "tooltip": "(-) 포켓몬 배틀 도전\n(+) 벌레타입 기술을 가르침",
```suggestion
      "tooltip": "(-) 포켓몬 배틀 도전\n(+) 벌레 타입 기술을 가르침",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +      "disabled_tooltip": "벌레타입 포켓몬이 없다.",
```suggestion
      "disabled_tooltip": "벌레 타입 포켓몬이 없다.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +      "selected_0_to_1": "응? 너 {{numBugTypes}}마리 갖고 있구나...$너 같은 일반인한테 떠들다었다니, 산소가 아깝네…",
```suggestion
      "selected_0_to_1": "응? 너 {{numBugTypes}}마리밖에 안 갖고 있구나...$너 같은 일반인한테 떠들었다니, 쓸데없이 입만 아팠네…",
```
'산소가 아깝다'라는 표현이 한국어로 조금 직관적이지 않은 듯해서 사전에서 'waste one's breath'의 해석으로 제시한 '입만 아프다'라는 표현을 제안해 봅니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +      "selected_6": "우와!\n{{numBugTypes}}마리 모두 벌레타입!$너도 나만큼 벌레 타입을 사랑하는거지?$이걸 가져가!\n동지의 증표로 나눠줄게!"
```suggestion
      "selected_2_to_3": "어라, 너 {{numBugTypes}}마리 갖고 있구나!\n나쁘지 않아.$내가 더 많이 잡는 데 도움이 될만한 걸 줄게!",
      "selected_4_to_5": "뭐야? 너 벌레 타입을 {{numBugTypes}}마리나 갖고 있네?\n좋아!$아직 수준엔 못 미치지만, 너한테 내 옛날 모습이 보여!\n$이걸 받거라, 내 제자여…!",
      "selected_6": "우와!\n{{numBugTypes}}마리 모두 벌레 타입!$너도 나만큼 벌레 타입을 사랑하는 거지?$이걸 가져가!\n동지의 증표로 나눠줄게!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +      "selected_dialogue": "우와! {{selectedItem}}, 나한테 주는거야?\n너 꽤 괜찮은 꼬마구나!$고마우니깐,\n나도 너한테 특별한 선물을 줄게!$가보로 전해져 내려온 귀한 물건이지만,\n너한테 주고 싶어!"
```suggestion
      "selected_dialogue": "우와! {{selectedItem}}, 나한테 주는 거야?\n너 꽤 괜찮은 꼬마구나!$고마우니깐,\n나도 너한테 특별한 선물을 줄게!$가보로 전해져 내려온 귀한 물건이지만\n너한테 주고 싶어!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/bug-type-superfan-dialogue.json
> +  "battle_won": "너의 지식과 기술들이 우리 약점을 완벽하게 파고들었어.$귀중한 경험을 했으니,\n나도 벌레타입 기술을 하나 가르쳐 줄게!",
```suggestion
  "battle_won": "너의 지식과 기술들이 우리 약점을 완벽하게 파고들었어.$귀중한 경험을 했으니,\n나도 벌레 타입 기술을 하나 가르쳐 줄게!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/clowning-around-dialogue.json
> +  "intro_dialogue": "거기있는 어리버리한 바보씨, 화려한 배틀을 맞이할 각오를 하시길!\n이 싸움꾼 광대가 당신을 쓰러트리겠습니다!",
```suggestion
  "intro_dialogue": "거기 있는 어리버리한 바보씨, 화려한 배틀을 맞이할 각오를 하시길!\n이 싸움꾼 광대가 당신을 쓰러트리겠습니다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/clowning-around-dialogue.json
> +      "apply_ability_message": "어릿광대가 포켓몬 한 마리의 특성을 영구적으로 {{ability}}로 교환해주겠다고 제안했다!",
```suggestion
      "apply_ability_message": "어릿광대가 포켓몬 한 마리의 특성을 영구적으로 {{ability}}로 교환해 주겠다고 제안했다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +  "intro": "{{oricorioName}}[[가]] 외롭게 혼자 춤을 추고 있다.\n주변에 파트너도 없는 것 같다!",
```suggestion
  "intro": "{{oricorioName}}[[가]] 외로이 혼자 춤을 추고 있다.\n주변에 파트너도 없는 것 같다!",
```
의미는 달라지는 게 없는데 뭔가 조금 더 나은 듯하여 제안해 봅니다..

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "tooltip": "(-) 어려운 배틀\n(+) 바톤 획득",
```suggestion
      "tooltip": "(-) 어려운 배틀\n(+) 배턴 획득",
```
9세대부터 "바톤터치"가 "배턴터치"으로 바뀌었는데, 아이템 "Baton"이 전에 어떻게 번역되었는지 확인해봐야 할 듯합니다. 만약 그게 "바톤"이라면 맞춰서 "배턴"으로 바꿔야 할 것 같습니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "selected": "{{oricorioName}}[[는]] 혼란스러워하며 방어태세를 갖췄다!",
```suggestion
      "selected": "{{oricorioName}}[[는]] 혼란스러워하며 방어 태세를 갖췄다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro_dialogue": "거기, 너!$난 포켓몬의 숨겨진 힘을 끌어낼 수 있는\n새로운 장치를 만드는 중이거든!$포켓몬을 분자 수준에서 재결합해서\n훨씬 더 강력한 형태로 만드는거야.$히히...@d{64} 이걸 증명하려면 약간의 희ㅅ-\n음...@d{32} 실험 대상이 필요해.",
```suggestion
  "intro_dialogue": "거기, 너!$난 포켓몬의 숨겨진 힘을 끌어낼 수 있는\n새로운 장치를 만드는 중이거든!$포켓몬을 분자 수준에서 재결합해서\n훨씬 더 강력한 형태로 만드는 거야.$히히…@d{64} 이걸 증명하려면 약간의 희ㅅ-\n음…@d{32} 실험 대상이 필요해.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "description": "수상한 남자가\n몬스터볼을 여러 개 들고 있습니다.\n\"내가 보장할게! 네 포켓몬을 한 마리만 줘!\n대신 아주 좋은 몬스터볼을 줄 테니까. 히히\"",
```suggestion
  "description": "수상한 남자가\n몬스터볼을 여러 개 들고 있습니다.\n\"내가 보장할게! 네 포켓몬을 한 마리만 줘!\n대신 아주 좋은 몬스터볼을 줄 테니까. 히히…\"",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "intro": "너덜너덜한 외투를 입은\n이상한 남자가 길을 막았다....",
```suggestion
  "intro": "너덜너덜한 외투를 입은\n이상한 남자가 길을 막았다….",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected_dialogue": "어디 보자, {{pokeName}}[[가]] 좋겠군!$명심해, 나쁜 일이 생겨도\n책임 못 지니까!@d{32} 히히...",
```suggestion
      "selected_dialogue": "어디 보자, {{pokeName}}[[가]] 좋겠군!$명심해, 나쁜 일이 생겨도\n책임 못 지니까!@d{32} 히히…",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}[[는]] 이상한 기계에 들어갔다...$표시등이 깜빡이고 이상한 소리가\n기계에서 들려오기 시작했다!$...@d{96} 기계에서 뭔가가\n맹렬한 기세로, 뛰쳐나왔다!"
```suggestion
      "selected_message": "남자는 로그볼 5개를 건넸다.${{pokeName}}[[는]] 이상한 기계에 들어갔다…$표시등이 깜빡이고 이상한 소리가\n기계에서 들려오기 시작했다!$…@d{96} 기계에서 뭔가가\n맹렬한 기세로 뛰쳐나왔다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/dark-deal-dialogue.json
> +  "outro": "꺼림직한 만남을 뒤로 하고,\n침착하게 자리를 떠났다."
```suggestion
  "outro": "꺼림직한 만남을 뒤로 하고\n침착하게 자리를 떠났다."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/delibirdy-dialogue.json
> +  "outro": "{{delibirdName}} 무리가 행복하게 뒤뚱거리며 저 멀리 날아간다..$정말 별난 선물교환이었다!"
```suggestion
  "outro": "{{delibirdName}} 무리가 행복하게 뒤뚱거리며 저 멀리 날아간다…$정말 별난 선물교환이었다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/department-store-sale-dialogue.json
> +  "intro_dialogue": "안녕!\n너도 대박 세일을 노리고 온 거지?$세일 기간동안 무료로 아이템을 교환할 수 있는 특별한 쿠폰이 있어!$남는 쿠폰을 나눠줄게!",
```suggestion
  "intro_dialogue": "안녕!\n너도 대박 세일을 노리고 온 거지?$세일 기간 동안 무료로 아이템을 교환할 수 있는 특별한 쿠폰이 있어!$남는 쿠폰을 나눠줄게!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "intro_dialogue": "안녕하세요!\n저희 학생들에게 잠시 시간 좀 내주실 수 있을까요?$포켓몬의 기술에 대해서 가르치고 있는데\n실제 기술을 보게되면 좋아할 것 같아서요.$괜찮으시면 저희에게\n포켓몬이 사용할 수 있는 기술을 보여주실래요?",
```suggestion
  "intro_dialogue": "안녕하세요!\n저희 학생들에게 잠시 시간 좀 내주실 수 있을까요?$포켓몬의 기술에 대해서 가르치고 있는데\n실제 기술을 보게 되면 좋아할 것 같아서요.$괜찮으시면 저희에게\n포켓몬이 배우고 있는 기술을 보여주실래요?",
```
한국어로 직역하면 조금 중의적인 요소가 있는 듯하여 '배우고 있는'으로 제안해 봅니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "description": "학교 선생님이 포켓몬의 기술 시연을 부탁했습니다.\n선택한 기술에 따라, 선생님이 뭔가 쓸 만한 걸 주실 수도 있을 것 같네요.",
```suggestion
  "description": "학교 선생님이 포켓몬의 기술 시연을 부탁했습니다.\n어떤 기술을 선택했는지에 따라 선생님이 뭔가 쓸 만한 걸 주실 수도 있을 것 같네요.",
```
조금 더 의미를 명확하게 고쳐서 제안해 봅니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/field-trip-dialogue.json
> +  "incorrect": "...$이건 {{moveCategory}} 기술이 아닌데요!\n죄송하지만, 저희는 이만 가볼게요.$얘들아 이리오렴.\n다른 곳에서는 제대로된 기술 시연을 볼 수 있을거야.",
```suggestion
  "incorrect": "…$이건 {{moveCategory}} 기술이 아닌데요!\n죄송하지만, 저희는 이만 가볼게요.$얘들아 이리 오렴.\n다른 곳에서는 제대로 된 기술 시연을 볼 수 있을 거야.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +  "intro": "매캐한 연기와 화산재의 폭풍을 맞닥뜨렸다!",
```suggestion
  "intro": "매캐한 연기와 화산재 폭풍을 맞닥뜨렸다!",
```
'의'를 빼는 편이 조금 자연스럽다고 생각합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +  "description": "소용돌이치는 화산재와 불씨로 인해 앞이 거의 보이질 않습니다.\n이런 데는 무언가… 원인이 있는 것 같습니다.\n그렇지만 이정도로 큰 규모라면 뒤에 도대체 뭐가 있는 걸까요?",
```suggestion
  "description": "소용돌이치는 화산재와 불씨로 인해 앞이 거의 보이질 않습니다.\n이런 일에는 무언가… 원인이 있는 것 같습니다.\n그렇지만 이 정도로 큰 규모라면 뒤에 도대체 뭐가 있는 걸까요?",
```
조금 더 명확하게 수정하여 제안합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +      "selected": "쉘터를 향해 고분고투하는 동안\n재와 불씨로 인해 심각한 피해를 입었다!$모든 포켓몬이 HP가 20% 피해를 받았다!",
```suggestion
      "selected": "피할 만한 곳을 찾으며 고군분투하는 동안\n재와 불씨로 인해 심각한 피해를 입었다!$모든 포켓몬이 HP의 20% 피해를 받았다!",
```
표준 표기법에 맞게 "셸터" 혹은 "피할 곳", "피할 만한 곳" 정도가 좋지 않을까 제안합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +      "label": "불꽃 포켓몬들 도움받기",
```suggestion
      "label": "불꽃 포켓몬들의 도움 받기",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +      "selected": "{{option3PrimaryName}}[[과]] {{option3SecondaryName}}의 도움으로,\n구애의 춤을 추고 있는 {{volcaronaName}} 두 마리를 발견했다!$다행히 포켓몬들이 그 두 마리를을 진정시키고,\n문제없이 신혼여행을 떠나보냈다."
```suggestion
      "selected": "{{option3PrimaryName}}[[과]] {{option3SecondaryName}}의 도움으로,\n구애의 춤을 추고 있는 {{volcaronaName}} 두 마리를 발견했다!$다행히 포켓몬들이 그 두 마리를 진정시키고,\n문제없이 신혼여행을 떠나보냈다."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fight-or-flight-dialogue.json
> +  "title": "도망치거나, 맞서 싸우거나",
```suggestion
  "title": "도망치거나 맞서 싸우거나",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/modifier-type.json
>        "description": "지니게 하면 {{stat}} 종족값을 10% 올려준다. 개체값이 높을수록 더 많이 누적시킬 수 있다."
```suggestion
      "description": "지니게 하면 {{stat}} 종족치를 10% 올려준다. 개체값이 높을수록 더 많이 누적시킬 수 있다."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/modifier-type.json
> +      "description": "모든 종족값을 {{statValue}}만큼 {{increaseDecrease}}. 단단지의 {{blessCurse}}[[를]] 받았다.",
```suggestion
      "description": "모든 종족치를 {{statValue}}만큼 {{increaseDecrease}}. 단단지의 {{blessCurse}}[[를]] 받았다.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/modifier-type.json
> +      "description": "{{stats}} 종족값을 {{statValue}}만큼 올려준다. 이상한 꿈을 꾸고 얻었다."
```suggestion
      "description": "{{stats}} 종족치를 {{statValue}}만큼 올려준다. 이상한 꿈을 꾸고 얻었다."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/modifier-type.json
> +    "MYSTERY_ENCOUNTER_OLD_GATEAU": { "name": "숲의양갱", "description": "{{stats}} 종족값을 {{statValue}}만큼 올려준다." },
```suggestion
    "MYSTERY_ENCOUNTER_OLD_GATEAU": { "name": "숲의양갱", "description": "{{stats}} 종족치를 {{statValue}}만큼 올려준다." },
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-strong-stuff-dialogue.json
> +      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족값이 각각 {{reductionValue}}만큼 감소했다!$하지만 다른 포켓몬들은 놀
```suggestion
      "selected_2": "@f{150}정신을 차리고 나니, {{shuckleName}}[[는]] 사라지고\n주스도 완전히 비었다.${{highBstPokemon1}}[[과]] {{highBstPokemon2}}[[는]]\n굉장히 무기력해졌다!$두 포켓몬의 종족치가 각각 {{reductionValue}}만큼 감소했다!$하지만 다른 포켓몬들은 놀라울만큼 활력이 넘친다!\n다른 포켓몬들의 종족치가 각각 {{increaseValue}}만큼 증가했다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fight-or-flight-dialogue.json
> +      "selected": "강한 포켓몬과 상품을 남겨둔 채\n당신은 계속 나아간다."
```suggestion
      "selected": "강한 포켓몬과 전리품을 남겨둔 채\n당신은 계속 나아간다."
```
"상품"에는 사고파는 물건이라는 의미가 있어서 다른 단어로 바꾸는 게 나을 듯합니다. 일단 "전리품" 정도로 해 보았는데, 문제는 이 상황에서는 빼앗지 않은 물건을 칭하는 것이라 더 나은 단어가 있을 것 같기는 합니다...

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "description": "상품이 걸린 게임이 진행 중입니다!\n@[TOOLTIP_TITLE]{3턴}안에 {{wobbuffetName}}[[를]] @[TOOLTIP_TITLE]{기절시키지 않고 HP를 1}에 가깝게 만들어서, {{wobbuffetName}}이 해머기계에 최고로 강력한 카운터를 날리도록 해야합니다.\n하지만 조심하세요! 만약 {{wob
```suggestion
  "description": "상품이 걸린 게임이 진행 중입니다!\n@[TOOLTIP_TITLE]{3턴} 안에 {{wobbuffetName}}[[를]] @[TOOLTIP_TITLE]{기절시키지 않고 HP를 1}에 가깝게 만들어서, {{wobbuffetName}}이 해머기계에 최고로 강력한 카운터를 날리도록 해야합니다.\n하지만 조심하세요! 만약 {{wobbuffetName}}[[가]] 기절해버리면, 치료비를 내야 할테니까요!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "query": "게임에 참가해볼까요?",
```suggestion
  "query": "게임에 참가해 볼까요?",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "ko": "안 돼! {{wobbuffetName}}[[가]] 기절해버렸다!$게임에 지고 {{wobbuffetName}} 병원비까지 내야할 판이다…",
```suggestion
  "ko": "안 돼! {{wobbuffetName}}[[가]] 기절해버렸다!$게임에 지고 {{wobbuffetName}}의 병원비까지 내야할 판이다…",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "turn_remaining_1": "남은 턴은 단 한번!",
```suggestion
  "turn_remaining_1": "남은 턴은 단 한 번!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "end_game": "거기까지!${{wobbuffetName}}[[가]] 한껏 충전한 카운터를 날릴준비를 한다@d{16}.@d{16}.@d{16}.",
```suggestion
  "end_game": "거기까지!${{wobbuffetName}}[[가]] 한껏 충전한 카운터를 날릴 준비를 한다@d{16}.@d{16}.@d{16}.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "best_result": "{{wobbuffetName}}[[가]] 기계를 때려부술 기세로 내리쳤다!!!$기계 맨 위에 달려있던 벨이\n아예 박살나 날아가 버렸다!$최고 1등상을 얻었다!",
```suggestion
  "best_result": "{{wobbuffetName}}[[가]] 기계를 때려 부술 기세로 내리쳤다!!!$기계 맨 위에 달려 있던 벨이\n아예 박살나 날아가 버렸다!$최고 1등상을 얻었다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/fun-and-games-dialogue.json
> +  "great_result": "{{wobbuffetName}}[[가]] 버튼을 박살낼 듯 내려쳤다!!$벨에 닿을랑 말랑한 곳까지 올라갔다!\n아깝다!!$2등상을 받았다!",
```suggestion
  "great_result": "{{wobbuffetName}}[[가]] 버튼을 박살낼 듯 내려쳤다!!$벨에 닿을락 말락 하는 곳까지 올라갔다!\n아깝다!!$2등상을 받았다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/global-trade-system-dialogue.json
> +      "label": "미라클교환 한다",
```suggestion
      "label": "미라클 교환을 한다",
```
7세대 본가 표기를 보니 "미라클 교환"으로 띄어쓰기가 있습니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/global-trade-system-dialogue.json
> +      "selected": "교환할 시간 없다!\n서둘러 떠난다!"
```suggestion
      "selected": "교환할 시간이 없다!\n서둘러 떠났다."
```
수정 제안 합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +  "intro": "정처없이 바다를 헤메다보니,\n정말로 당신은 아무 데도 갈 수 없게 되었다.",
```suggestion
  "intro": "정처 없이 바다를 헤메었지만,\n당신은 아무런 성과도 거두지 못했습니다.",
```
"get nowhere"은 사전에서 "성공하지 못하다", "아무 성과를 못 보다"라는 의미로 풀고 있어서 수정 제안을 합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +      "label": "정처없이 방황한다",
```suggestion
      "label": "정처 없이 방황한다",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/lost-at-sea-dialogue.json
> +      "selected": "마침내 기억하는 곳에 다다를 때까지,\n정처없이 배를 타고 떠돌아다닌다.$길고 긴 표류에 포켓몬과 당신 모두 지쳐버렸다."
```suggestion
      "selected": "마침내 기억하는 곳에 다다를 때까지\n정처 없이 배를 타고 떠돌아다닌다.$길고 긴 표류에 포켓몬과 당신 모두 지쳐버렸다."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +      "label": "신중해보이는 도전자",
```suggestion
      "label": "신중해 보이는 도전자",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +      "label": "강해보이는 도전자",
```suggestion
      "label": "강해 보이는 도전자",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/mysterious-challengers-dialogue.json
> +    "selected": "선택한 트레이너가 앞으로 걸어나온다..."
```suggestion
    "selected": "선택한 트레이너가 앞으로 걸어 나온다…"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/mysterious-chest-dialogue.json
> +  "intro": "이건...@d{32} 뭐지?",
```suggestion
  "intro": "이건…@d{32} 뭐지?",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/mysterious-chest-dialogue.json
> +  "description": "아름답게 장식된 상자가 바닥에 놓여있습니다. 보통 이럴 땐, 안에 뭔가 좋은 것이 있는 것이 인지상정...\n그렇지 않을까요?",
```suggestion
  "description": "아름답게 장식된 상자가 바닥에 놓여 있습니다. 보통 이럴 땐, 안에 뭔가 좋은 게 들었다고 생각하는 것이 인지상정…\n그렇지 않을까요?",
```
"인지상정"은 현상보다는 어떤 행위나 마음 같은 것에 사용해야 해서 약간 고쳐 보았습니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/mysterious-chest-dialogue.json
> +      "selected": "당신이 상자안에서 찾은 것은...",
```suggestion
      "selected": "당신이 상자안에서 찾은 것은…",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/part-timer-dialogue.json
> +  "description": "해야 할 일들이 산더미같이 쌓여 있네요.\n포켓몬이 일을 얼마나 잘하는지에 따라,\n일당을 더 많이 받을 수도, 더 적게 받을 수도 있을 것 같습니다.",
```suggestion
  "description": "해야 할 일이 산더미같이 쌓여 있네요.\n포켓몬이 일을 얼마나 잘하는지에 따라\n일당을 더 많이 받을 수도, 더 적게 받을 수도 있을 것 같습니다.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/part-timer-dialogue.json
> +  "query": "어떤 아르바이트를 해볼까요?",
```suggestion
  "query": "어떤 아르바이트를 해 볼까요?",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/part-timer-dialogue.json
> +      "label": "창고정리",
```suggestion
      "label": "창고 정리",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/part-timer-dialogue.json
> +      "selected": "{{option3PrimaryName}}[[는]] {{option3PrimaryMove}}[[로]]\n하루종일 손님들을 끌어모았다!"
```suggestion
      "selected": "{{option3PrimaryName}}[[는]] {{option3PrimaryMove}}[[로]]\n하루 종일 손님들을 끌어모았다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/part-timer-dialogue.json
> +  "pokemon_tired": "{{selectedPokemon}}[[가]] 지친 것 같다!\n모든 기술의 PP가 2까지 줄었다!",
```suggestion
  "pokemon_tired": "{{selectedPokemon}}[[가]] 지친 것 같다!\n모든 기술의 PP가 2로 감소했다!",
```
"-까지 줄었다"라고 하면 "1~2만큼 줄었다"라고 잘못 읽힐 수도 있을 듯하여 수정했습니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/safari-zone-dialogue.json
> +  "description": "여기에는 오만가지 희귀하고 특별한 포켓몬들이 살고 있습니다! 최대 3마리까지, 특별한 포켓몬을 만나고 잡을 기회가 있답니다.\n\n하지만 조심하세요! 잡기도 전에 포켓몬이 도망칠 수도 있으니까요!",
```suggestion
  "description": "여기에는 오만 가지 희귀하고 특별한 포켓몬들이 살고 있습니다! 특별한 포켓몬을 최대 3마리까지 만나고 잡을 기회가 있답니다.\n\n하지만 조심하세요! 잡기도 전에 포켓몬이 도망칠 수도 있으니까요!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +  "description": "남자가 코트를 살짝 열어 보여주자,\n코트 안쪽에 포켓몬 영양제들이 빼곡히 들어있습니다.\n그가 부른 가격은 아주 매력적입니다. 좋아도 너무 좋군요…\n그는 두가지 선택지를 제시했습니다.",
```suggestion
  "description": "남자가 코트를 살짝 열어 보여주자,\n코트 안쪽에 포켓몬 영양제들이 빼곡히 들어있는 것이 보입니다.\n그가 부른 가격은 아주 매력적입니다. 좋아도 너무 좋군요…\n그는 두가지 선택지를 제시했습니다.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +      "selected": "흥, 너같은 겁쟁이한테는 안 팔아."
```suggestion
      "selected": "흥, 너 같은 겁쟁이한테는 안 팔아."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +  "cheap_side_effects": "그런데 약이 부작용이 있는 것 같다!${{selectedPokemon}}[[가]] 약간 고통스러워 한다.\n성격이 {{newNature}}[[로]] 변해버렸다!",
```suggestion
  "cheap_side_effects": "그런데 약이 부작용이 있는 것 같다!${{selectedPokemon}}[[가]] 약간 고통스러워한다.\n성격이 {{newNature}}[[로]] 변해버렸다!",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +  "no_bad_effects": "딱히 부작용도 없는 것 같다!"
```suggestion
  "no_bad_effects": "딱히 부작용은 없는 것 같다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-winstrate-challenge-dialogue.json
> +  "description": "모두 5명인 연승가족들이 승부를 바라고 있습니다!\n가족 모두를 연달아 쓰러뜨릴 수 있다면 어마어마한 상품을 줄 겁니다.\n하지만 이걸 감당할 수 있을까요?",
```suggestion
  "description": "모두 5명인 연승가족이 승부를 바라고 있습니다!\n가족 모두를 연달아 쓰러뜨릴 수 있다면 어마어마한 보상을 줄 겁니다.\n하지만 이걸 감당할 수 있을까요?",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-winstrate-challenge-dialogue.json
> +      "selected": "아쉽군. 근데, 자네 포켓몬들 좀 지쳐보이는구만,\n조금 쉬고 가지 않을텐가?"
```suggestion
      "selected": "아쉽군. 그런데 자네 포켓몬들 좀 지쳐보이는구만,\n조금 쉬고 가지 않을텐가?"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/the-winstrate-challenge-dialogue.json
> +  "victory": "우리의 시련을 모두 극복하다니 축하하네!$먼저, 이 바우처를 주겠네.",
```suggestion
  "victory": "우리의 시련을 모두 극복하다니 축하하네!$먼저 이 바우처를 주겠네.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/training-session-dialogue.json
> +  "description": "발견한 기구들은 포켓몬들을 훈련시키는 데 쓸 수 있을 것 같습니다!\n파티의 다른 포켓몬들과 싸우면서 원하는 방식으로 훈련해보면 어떨까요?",
```suggestion
  "description": "발견한 기구들은 포켓몬들을 훈련시키는 데 쓸 수 있을 것 같습니다!\n파티의 다른 포켓몬들과 싸우면서 원하는 방식으로 훈련해 보면 어떨까요?",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/training-session-dialogue.json
> +      "tooltip": "(-) 쉬운 배틀 \n(+) 선택 포켓몬 무작위 개체값 2가지 향상",
```suggestion
      "tooltip": "(-) 쉬운 배틀 \n(+) 선택 포켓몬 무작위 개체치 2가지 향상",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/training-session-dialogue.json
> +      "finished": "훈련을 마친 {{selectedPokemon}}[[는]] 조금 지쳤지만 뿌듯해보인다!${{selectedPokemon}}의 {{stat1}}[[과]] {{stat2}}[[가]] 상승했다!"
```suggestion
      "finished": "훈련을 마친 {{selectedPokemon}}[[는]] 조금 지쳤지만 뿌듯해 보인다!${{selectedPokemon}}의 {{stat1}}[[과]] {{stat2}}[[가]] 상승했다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/training-session-dialogue.json
> +      "finished": "훈련을 마친 {{selectedPokemon}}[[는]] 조금 지쳤지만 뿌듯해보인다!${{selectedPokemon}}의 성격이 {{nature}}[[로]] 바뀌었다!"
```suggestion
      "finished": "훈련을 마친 {{selectedPokemon}}[[는]] 조금 지쳤지만 뿌듯해 보인다!${{selectedPokemon}}의 성격이 {{nature}}[[로]] 바뀌었다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/training-session-dialogue.json
> +      "finished": "훈련을 마친 {{selectedPokemon}}[[는]] 조금 지쳤지만 뿌듯해보인다!${{selectedPokemon}}의 특성이 {{ability}}[[로]] 바뀌었다!"
```suggestion
      "finished": "훈련을 마친 {{selectedPokemon}}[[는]] 조금 지쳤지만 뿌듯해 보인다!${{selectedPokemon}}의 특성이 {{ability}}[[로]] 바뀌었다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +  "description": "쓰레기 더미가 눈앞에 펼쳐져있습니다.\n그 속에서 가치있는 물건을 찾을 수도 있겠죠.\n하지만 그 물건들을 얻기 위해\n정말로 오물을 뒤집어쓰고 싶으신가요?",
```suggestion
  "description": "쓰레기 더미가 눈앞에 펼쳐져 있습니다.\n그 속에서 가치 있는 물건을 찾을 수도 있겠죠.\n하지만 그 물건들을 얻기 위해\n정말로 오물을 뒤집어쓰고 싶으신가요?",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "쓰레기 더미를 헤집고 다니며, 오물을 뒤집어썼다.$지금 이 상태로는, 아무리 친절한 점원이라도\n물건을 제 가격에 안 팔 것 같다!$앞으로 상점에서 파는 회복약을 훨씬 비싸게 사야 한다.$하지만, 쓰레기에서 엄청난 물건들을 발견했다!"
```suggestion
      "selected": "쓰레기 더미를 헤집고 다니며 오물을 뒤집어썼다.$지금 이 상태라면 아무리 친절한 점원이라도\n물건을 제 가격에 안 팔 것 같다!$앞으로는 상점에서 파는 회복약을 훨씬 비싸게 사야 한다.$하지만 쓰레기에서 엄청난 물건들을 발견했다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected": "쓰레기 더미 주변을 거닐며,\n이게 여기 어떻게 생겨난건지 단서를 찾아본다...",
```suggestion
      "selected": "쓰레기 더미 주변을 거닐며,\n이게 여기 어떻게 생겨난 건지 단서를 찾아본다…",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/trash-to-treasure-dialogue.json
> +      "selected_2": "갑자기 쓰레기 더미가 움직였다!\n쓰레기가 아니고, 포켓몬이었다!"
```suggestion
      "selected_2": "갑자기 쓰레기 더미가 움직였다!\n쓰레기가 아니라 포켓몬이었다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/uncommon-breed-dialogue.json
> +  "description": "저 {{enemyPokemon}}[[는]] 어딘가 다른 {{enemyPokemon}}[[과]]는 달라보입니다. @[TOOLTIP_TITLE]{아마 특별한 기술을 알고 있을지도?}\n평범하게 배틀로 잡을 수도 있지만, 친구가 되는 방법도 있을 것 같습니다.",
```suggestion
  "description": "저 {{enemyPokemon}}[[는]] 다른 {{enemyPokemon}}[[과]]는 어딘가 달라보입니다. @[TOOLTIP_TITLE]{아마 특별한 기술을 알고 있을지도?}\n평범하게 배틀로 잡을 수도 있지만, 친구가 되는 방법도 있을 것 같습니다.",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/uncommon-breed-dialogue.json
> +      "tooltip": "(-) 까다로운 배틀\n(+) 포획가능한 강한 적",
```suggestion
      "tooltip": "(-) 까다로운 배틀\n(+) 포획 가능한 강한 적",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/uncommon-breed-dialogue.json
> +      "selected": "{{option3PrimaryName}}[[가]] {{option3PrimaryMove}}[[를]] 사용해,\n{{enemyPokemon}}를 매료시켰다!${{enemyPokemon}}[[는]] 동료가 되고 싶어하는 것 같다!"
```suggestion
      "selected": "{{option3PrimaryName}}[[가]] {{option3PrimaryMove}}[[를]] 사용해\n{{enemyPokemon}}를 매료시켰다!${{enemyPokemon}}[[는]] 동료가 되고 싶어하는 것 같다!"
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +  "title": "영양제 딜러(?)",
```suggestion
  "title": "영양제(?) 딜러",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/weird-dream-dialogue.json
> +  "intro": "어두운 실루엣의 여자가 앞을 막아선다.\n그녀에게서 뭔가 불안한 느낌이 든다…….",
```suggestion
  "intro": "어떤 여자의 실루엣이 앞을 막아섰다.\n그녀에게서 뭔가 불안한 느낌이 든다…….",
```
"실루엣" 자체에 어두운 윤곽이라는 뜻이 있다 보니 "실루엣"이라는 단어를 쓴다면 "어두운"은 넣지 않아도 좋을 듯합니다.

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/weird-dream-dialogue.json
> +  "description": "여자의 말이 머리속에서 메아리처럼 울려 퍼집니다. 이건 단순히 한 사람의 목소리가 아닙니다. 모든 시간선과 현실들에서 온 수많은 사람들의 목소리입니다.\n당신은 어지러움을 느끼기 시작하고, 한 질문이 머릿속을 맴돌기 시작합니다…\n\n@[TOOLTIP_TITLE]{\"너의 미래와 과거를 봤어….저기…너도 그게 보이는 걸까?
```suggestion
  "description": "여자의 말이 머릿속에서 메아리처럼 울려 퍼집니다. 이건 단순히 한 사람의 목소리가 아닙니다. 모든 시간선과 현실에서 온 수많은 사람들의 목소리입니다.\n당신은 어지러움을 느끼기 시작하고, 한 질문이 머릿속을 맴돌기 시작합니다…\n\n@[TOOLTIP_TITLE]{\"너의 미래와 과거를 봤어….저기… 너도 그게 보이는 걸까?\"}",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/weird-dream-dialogue.json
> +      "selected": "그녀는 당신에게 손을 뻗었고,\n이내 모든 것이 깜깜해졌다.$그리고…@d{64} 당신은 모든 것이 보인다.\n모든 시간선, 또다른 당신의 모습,\n 과거와 미래.$당신을 만들어온 모든 것,\n당신이 될 모든 것…@d{64}",
```suggestion
      "selected": "그녀는 당신에게 손을 뻗었고,\n이내 모든 것이 깜깜해졌다.$그리고…@d{64} 당신은 모든 것이 보인다.\n모든 시간선, 또 다른 당신의 모습,\n 과거와 미래.$당신을 만들어온 모든 것,\n당신이 될 모든 것…@d{64}",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/weird-dream-dialogue.json
> +      "cutscene": "당신의 포켓몬들이 보인다.@d{32} 모든 현실이\n합쳐져 새로운 무언가가 되고있다…@d{64}",
```suggestion
      "cutscene": "당신의 포켓몬들이 보인다.@d{32} 모든 현실이\n합쳐져 새로운 무언가가 되고 있다…@d{64}",
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/weird-dream-dialogue.json
> +      "dream_complete": "잠에서 깨어나자, 여자는 사라진 것 같다.\n사람이 아니라 유령이었을지도…$.@d{32}.@d{32}.@d{32}?$파티의 포켓몬이 바뀌었다…?$…아니 원래부터 이 상태였는지도 모른다."
```suggestion
      "dream_complete": "잠에서 깨어나자, 여자는 사라진 것 같다.\n사람이 아니라 유령이었을지도…$.@d{32}.@d{32}.@d{32}?$파티의 포켓몬이 바뀌었다…?$…아니, 원래부터 이 상태였는지도 모른다."
```

2024-09-18 09:52 UTC, returntoice commented on src/locales/ko/mystery-encounters/weird-dream-dialogue.json
> +      "selected": "당신을 무감각하게 만들던 손아귀에서 벗어나,\n정신을 차리고 서둘러 자리를 떠났다.$간신히 정신을 추스르고 멈춰서서\n파티의 포켓몬들을 확인했다.$이유는 알 수 없지만\n파티의 모든 포켓몬 레벨이 약간 줄어들었다!"
```suggestion
      "selected": "당신을 무감각하게 만들던 손아귀에서 벗어나,\n정신을 차리고 서둘러 자리를 떠났다.$간신히 정신을 추스르고 멈춰 서서\n파티의 포켓몬들을 확인했다.$이유는 알 수 없지만\n파티의 모든 포켓몬 레벨이 약간 줄어들었다!"
```

2024-09-18 09:53 UTC, KimJeongSun commented on src/locales/ko/dialogue.json
> +      "2": "더는 헤매거나 하지 않는다는 것을 너에게 보여줄게!"
<img width="853" alt="image" src="https://github.com/user-attachments/assets/a027962e-1245-435b-9536-863827a047f8">

2024-09-18 09:57 UTC, KimJeongSun commented on src/locales/ko/modifier-select-ui-handler.json
> +  "continueNextWaveButton": "진행하기",
상점 창에서 나오는 메시지입니다.
다른 버튼명과 동일하게 명사형으로 번역했습니다.

2024-09-18 09:59 UTC, KimJeongSun commented on src/locales/ko/mystery-encounter-messages.json
> +  "cancel_option": "조우 선택지로 돌아가기",
이부분은 인게임에서 어떻게 쓰이고 있는지 확인하지 못했습니다. 나중에 확인하시면 수정 제안 다시 부탁드립니다

2024-09-18 10:06 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/absolute-avarice-dialogue.json
> +  "description": "당신이 방심한 틈에 {{greedentName}}[[가]] 나무열매를 모두 훔쳐가버렸습니다!\n\n{{greedentName}}[[는]] 나무열매를 먹으려다가,\n잠시 멈춰서 당신을 재밌다는 듯 바라보고 있습니다.",
```suggestion
  "description": "당신이 방심한 틈에 {{greedentName}}[[가]] 나무열매를 모두 훔쳐 가버렸습니다!\n\n{{greedentName}}[[는]] 나무열매를 먹으려다가,\n잠시 멈춰서 당신을 재밌다는 듯 바라보고 있습니다.",
```

2024-09-18 10:18 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/dancing-lessons-dialogue.json
> +      "tooltip": "(-) 어려운 배틀\n(+) 바톤 획득",
바톤 입니다. 나중에 그부분은 PR 부탁드려요

2024-09-18 10:29 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +      "label": "불꽃 포켓몬들 도움받기",
<img width="1717" alt="image" src="https://github.com/user-attachments/assets/0862c2ac-ab14-44b7-91b4-1bea0aa45370">
한글자만 줄여보죠 아래도 가능하구요
```suggestion
      "label": "불꽃 포켓몬의 도움받기",
```

2024-09-18 10:31 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/fight-or-flight-dialogue.json
> +      "selected": "강한 포켓몬과 상품을 남겨둔 채\n당신은 계속 나아간다."
일단은 이걸로

2024-09-18 10:36 UTC, KimJeongSun commented on src/locales/ko/mystery-encounters/fiery-fallout-dialogue.json
> +      "selected": "쉘터를 향해 고분고투하는 동안\n재와 불씨로 인해 심각한 피해를 입었다!$모든 포켓몬이 HP가 20% 피해를 받았다!",
```suggestion
      "selected": "쉘터를 향해 고분고투하는 동안\n재와 불씨로 인해 심각한 피해를 입었다!$모든 포켓몬이 HP의 20% 피해를 받았다!",
```

2024-09-18 11:02 UTC, merged

2024-09-18 11:07 UTC, returntoice commented on src/locales/ko/mystery-encounters/shady-vitamin-dealer-dialogue.json
> +  "cheap_side_effects": "그런데 약이 부작용이 있는 것 같다!${{selectedPokemon}}[[가]] 약간 고통스러워 한다.\n성격이 {{newNature}}[[로]] 변해버렸다!",
https://ko.dict.naver.com/#/correct/korean/info?seq=1624

다시 확인해 보니 '고통스러워하다'는 표제어는 아니지만 붙여 쓰는 게 원칙이라고 하네요. 나중에 수정할 일이 있다면 같이 고치면 좋을 듯합니다.